import {
  createSlice,
  type PayloadAction,
  createEntityAdapter,
} from "@reduxjs/toolkit";

import { fetchTodos } from "./asyncThunks";

type Todo = {
  id: number;
  text: string;
  completed: boolean;
  color?: string;
};

// The adapter manages a normalized slice: `{ ids: [], entities: {} }`.
// `selectId` defaults to `entity.id`, which matches our `Todo`, so no config
// is needed. It gives us CRUD helpers (addOne, setAll, removeMany, …) and a
// set of memoized selectors via `getSelectors`.
const todosAdapter = createEntityAdapter<Todo>();

// Merge the adapter's normalized shape with our own extra field.
const initialState = todosAdapter.getInitialState({
  isLoading: false,
});

type TodosState = typeof initialState;

const todosSlice = createSlice({
  name: "todos",
  initialState,
  reducers: {
    todoToggled(state, action: PayloadAction<number>) {
      // O(1) lookup by id instead of scanning an array.
      const todo = state.entities[action.payload];
      if (todo) {
        todo.completed = !todo.completed;
      }
    },
    colorSelected: {
      // `prepare` lets the action creator accept separate `todoId` and `color`
      // arguments and assemble them into the payload object.
      prepare(todoId: number, color: string) {
        return { payload: { todoId, color } };
      },
      reducer(state, action: PayloadAction<{ todoId: number; color: string }>) {
        const { color, todoId } = action.payload;
        const todo = state.entities[todoId];
        if (todo) {
          todo.color = color; 
        }
      },
    },
    todoDeleted(state, action: PayloadAction<number>) {
      todosAdapter.removeOne(state, action.payload);
    },
    allCompleted(state) {
      Object.values(state.entities).forEach((todo) => {
        todo.completed = true;
      });
    },
    completedCleared(state) {
      const completedIds = Object.values(state.entities)
        .filter((todo) => todo.completed)
        .map((todo) => todo.id);
      todosAdapter.removeMany(state, completedIds);
    },
    setTodos(state, action: PayloadAction<Todo[]>) {
      // `setAll` normalizes the array and replaces the whole collection.
      todosAdapter.setAll(state, action.payload);
      state.isLoading = false;
    },
  },
  // Handle the action types generated by the `fetchTodos` async thunk. These
  // live in `extraReducers` because the thunk owns the action types, not the
  // slice's `reducers`.
  extraReducers: (builder) => {
    builder
      .addCase(fetchTodos.pending, (state) => {
        state.isLoading = true;
      })
      .addCase(fetchTodos.fulfilled, (state, action) => {
        todosAdapter.setAll(state, action.payload);
        state.isLoading = false;
      })
      .addCase(fetchTodos.rejected, (state) => {
        state.isLoading = false;
      });
  },
});

export { todosSlice, todosAdapter };
export type { Todo, TodosState };

export default todosSlice.reducer;
